{% set name = "opentelemetry-instrumentation-dbapi" %}
{% set version = "0.28b1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/opentelemetry-instrumentation-dbapi-{{ version }}.tar.gz
  sha256: cad60eb1bce6e86c4c3c22109467f6ddb4a18ba81ba9d7a96db59f26d620d32f

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - opentelemetry-api ~=1.3
    - opentelemetry-instrumentation ==0.28b1
    - opentelemetry-semantic-conventions ==0.28b1
    - python >=3.6
    - wrapt <2.0.0,>=1.0.0
    # - opentelemetry-test ==0.24b0
    # - opentelemetry-test ==0.25b0
    # - opentelemetry-test ==0.25b2
    # - opentelemetry-test-utils ==0.26b1
    # - opentelemetry-test-utils ==0.27b0
    # - opentelemetry-test-utils ==0.28b0
    # - opentelemetry-test-utils ==0.28b1

test:
  imports:
    - opentelemetry
    - opentelemetry.instrumentation
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/open-telemetry/opentelemetry-python-contrib/tree/main/instrumentation/opentelemetry-instrumentation-dbapi
  summary: OpenTelemetry Database API instrumentation
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mariusvniekerk
