{% set name = "opentelemetry-instrumentation-dbapi" %}
{% set version = "0.27b0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/opentelemetry-instrumentation-dbapi-{{ version }}.tar.gz
  sha256: 30dfb32d87dcbd4c00f1e8875595652c9dc38d04b523b4135374122447340286

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - opentelemetry-api ~=1.3
    - opentelemetry-instrumentation ==0.27b0
    - opentelemetry-semantic-conventions ==0.27b0
    - python >=3.6
    - wrapt <2.0.0,>=1.0.0
    # - opentelemetry-test ==0.24b0
    # - opentelemetry-test ==0.25b0
    # - opentelemetry-test ==0.25b2
    # - opentelemetry-test-utils ==0.26b1
    # - opentelemetry-test-utils ==0.27b0

test:
  imports:
    - opentelemetry
    - opentelemetry.instrumentation
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/open-telemetry/opentelemetry-python-contrib/tree/main/instrumentation/opentelemetry-instrumentation-dbapi
  summary: OpenTelemetry Database API instrumentation
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mariusvniekerk
